# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsAppTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsAppTest
 pod 'Kingfisher', '~> 7.0'

end
